# baseURL es la URL base del sitio
baseURL: /
# El tema del sitio es hugo-apero
theme: hugo-apero
# El idioma del sitio es español
languageCode: es
# El título del sitio es "Edison Achalma, Econ"
title: Edison Achalma, Econ
# El autor del sitio es Edison Achalma
author: Edison Achalma
# El copyright se deja en blanco para sobrescribir el copyright generado automáticamente
# utilizando la información de la organización y el año actual
copyright: '' 
# Código de Google Analytics, dejar en blanco si no se usa
googleAnalytics: ''
# Nombre corto de Disqus, dejar en blanco si no se usa
# ver params.utterances para usar expresiones en lugar de Disqus
disqusShortname: '' 
# Formato de metadatos, establecido como yaml
metaDataFormat: yaml
# Contenido del enlace de retorno de la nota al pie, se establece como "↩"
footnoteReturnLinkContents: '&#8617;' # ↩
# Número de entradas por página, se establece en 5 para pruebas
# Seleccione el número que prefiera en función del diseño del blog elegido
paginate: 5
# Preservar los nombres de la taxonomía
preserveTaxonomyNames: yes
# ignoreFiles especifica los archivos que deben ignorarse al generar el sitio
ignoreFiles:
  # archivos con formato Rmd
  - \.Rmd$
  - \.Rmarkdown$
  # carpeta con archivos caché
  - _cache$
  # archivos .knit.md y .utf8.md
  - \.knit\.md$
  - \.utf8\.md$
# habilita el uso de emojis en el sitio
enableEmoji: yes
# Permalinks especifica la estructura de las URLs de los posts y páginas del sitio
permalinks:
  # para los posts del blog, la URL incluye el año, mes y título del post
 blog: "/blog/:year-:month-:slug/"
 # para las páginas de charlas, la URL incluye el nombre del archivo
 talk: "/talk/:filename/"
markup:
  # utiliza goldmark como procesador de markdown
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      # no utiliza saltos de línea duros en el HTML generado
      hardwraps: no
      # Permite contenido potencialmente inseguro (HTML) en el contenido de Markdown
      unsafe: yes
  highlight:
    # Utiliza el estilo de resaltado de código "github"
    # one of: https://xyproto.github.io/splash/docs/
    style: github
  tableOfContents:
    # La tabla de contenidos mostrará 2 niveles
    endLevel: 2
    # La ordenación de los elementos de la tabla de contenidos no está habilitada
    ordered: no
    # El nivel de inicio de la tabla de contenidos es el nivel 2
    startLevel: 2
# Parámetros de la página
params:
  # Tema personalizado para el sitio. Dejar en blanco para usar un tema incorporado
  # o especificar un archivo SCSS personalizado en la carpeta assets/ con el nombre del archivo.
  # Para usar colores hexadecimales en lugar de colores nombrados de Tachyons, incluir "hex" en el nombre del archivo.
  custom_theme: ''
  # Ejemplo de tema personalizado: fb-hex-achi
  # Fuente personalizada para el texto del sitio.
  # Opciones de serif: Fraunces / EB Garamond / Bitter
  # Opciones de sans-serif: Commissioner / Alegreya Sans / Metropolis
  # Si importa sus propias fuentes, también debe nombrarlas aquí.
  customtextFontFamily: Commissioner
  # Fuente personalizada para los encabezados del sitio. Ver opciones de customtextFontFamily.
  customheadingFontFamily: Fraunces
  # Descripción del sitio. Se usa en motores de búsqueda y cuando se comparte en redes sociales.
  description: Personal website and portfolio of Dr. Edison Achalma.
  # Favicon del sitio.
  favicon: /img/favicon.ico
  # Tipografía para encabezados
  headingFontFamily: sans-serif
  # URL para el logo del sitio
  logo: /img/blogophonic-mark-dark.png
  # Secciones principales del sitio
  mainSections:
    - blog
    - project
    - talk
  # Configuración para la visualización de fórmulas matemáticas  
  math:
    # Utilizar el renderer de KaTeX para visualizar fórmulas
    renderer: katex
  # Mostrar el menú de navegación en mayúsculas
  navallcaps: yes
  # Ciudad donde se encuentra la organización
  orgLocal: Ayacucho
  # Nombre de la organización
  orgName: Edison Achalma
  #  Imagen por defecto para compartir en redes sociales y buscadores. Place image file in `static` folder and specify image name here.
  sharing_image: /img/papillons.jpg
  # Social icons may appear on homepage and in site header or footer
  # Configure show/hide above - add as many as you like below
  # Icon pack "fab" includes brand icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
  # Icon pack "fas" includes solid icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
  # Icon pack "far" includes regular icons, see: https://fontawesome.com/icons?d=gallery&s=regular&m=free
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/achalmed
    - icon: facebook-square
      icon_pack: fab
      url: https://www.facebook.com/achalmed.23
    - icon: instagram
      icon_pack: fab
      url: https://www.instagram.com/explore/tags/apero/
    - icon: twitter
      icon_pack: fab
      url: https://twitter.com/achalmaedison
    - icon: impactstory
      icon_pack: ai
      url: https://impactstory.org/u/0000-0002-8082-1890
    - icon: orcid
      icon_pack: ai
      url: http://orcid.org/0000-0002-8082-1890
    - icon: rss
      icon_pack: fas
      url: /blog/index.xml
  # habilitar botones de redes sociales en el pie de página
  socialInFooter: yes
  # no mostrar botones de redes sociales en el encabezado
  socialInHeader: no
  # usar fuente sans-serif para el texto
  textFontFamily: sans-serif
  # usar tema "sky" use a built-in color theme one of: forest / grayscale / peach / plum / poppy / sky / violet / water
  theme: sky
  # usuario de Twitter para botón de compartir
  twitter: achalmaedison
  # Configuration of https://utteranc.es/ for comments
  utterances:
    # usar la ruta del artículo como término de la issue para los comentarios # url, pathname, or title
    issue_term: pathname
    # etiqueta para los comentarios
    label: 'comments :crystal_ball:'
    # nombre del repositorio donde se encuentran los comentarios
    repo_name: apreshill/apero
    # tema para los comentarios
    theme: boxy-light
    # habilitar el uso de Utterances para los comentarios
    use_utterances: yes
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
# Configure header
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
    - name: Contact
      title: Contact form
      url: /contact/
      weight: 2
    - name: Contributors
      title: Contributors
      url: /contributors/
      weight: 3
  header:
    - name: About
      title: About Blogophonic
      url: /about/
      weight: 1
    - name: Blog
      title: Blog
      url: /blog/
      weight: 2
    - name: Projects
      title: Project Portfolio
      url: /project/
      weight: 3
    - name: Talks
      title: Talks
      url: /talk/
      weight: 4
    - name: A collection
      title: A collection
      url: /collection/
      weight: 5
    - name: Elements
      title: Element Page
      url: /elements/
      weight: 6
# see https://gohugo.io/about/hugo-and-gdpr/
privacy:
  disqus:
    disable: no
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: no
    simple: yes
  twitter:
    disable: no
    enableDNT: yes
    simple: no
  vimeo:
    disable: no
    enableDNT: yes
    simple: yes
  youtube:
    disable: no
    privacyEnhanced: yes
