---
title: 'Comunismo Marxista y Maoísta: Ideologías y Movimientos Revolucionarios'
author: Edison Achalma Mendoza
date: '2023-03-04'
slug: comunismo-marxista-y-mao-sta-ideolog-as-y-movimientos-revolucionarios
categories:
  - Política
  - Sociedad
tags:
  - Comunismo
  - Marxismo
  - Maoísmo
subtitle: 'Explorando las raíces históricas, teóricas y prácticas del comunismo marxista y maoísta en la lucha por la igualdad y la justicia social.'
excerpt: ''
draft: no
series: ~
layout: single
---
## Introducción al comunismo marxista y maoísta
###  Definiciones y conceptos básicos

El comunismo marxista y maoísta son corrientes políticas y económicas que buscan la abolición de la propiedad privada y la creación de una sociedad sin clases sociales. A continuación, se presentan algunas definiciones y conceptos básicos relacionados con estas ideologías:

-   Comunismo: sistema político y económico basado en la propiedad colectiva de los medios de producción y la eliminación de la propiedad privada.
-   Marxismo: teoría política y económica basada en las ideas de Karl Marx y Friedrich Engels, que propone la lucha de clases y la revolución del proletariado para establecer una sociedad comunista.
-   Maoísmo: corriente del comunismo que se basa en las ideas del líder revolucionario chino Mao Zedong y enfatiza la importancia de la lucha armada y la movilización popular.
-   Proletariado: clase social que, en el marxismo, está compuesta por los trabajadores asalariados que no poseen los medios de producción y dependen del salario para subsistir.
-   Burguesía: clase social que, en el marxismo, posee los medios de producción y explota a la clase trabajadora para obtener beneficios.
-   Revolución: cambio radical y violento en las estructuras políticas, sociales y económicas de una sociedad.
-   Internacionalismo: principio del comunismo que defiende la solidaridad y la unidad de los trabajadores de todo el mundo para luchar contra la explotación capitalista.
-   Dictadura del proletariado: período de transición en el que la clase obrera toma el control del Estado y ejerce el poder político para establecer las bases de una sociedad comunista.

Estos son solo algunos de los conceptos básicos del comunismo marxista y maoísta, que se desarrollarán en mayor profundidad en el blog.

### Breve historia del movimiento comunista

El movimiento comunista tiene sus raíces en el siglo XIX, cuando el filósofo alemán Karl Marx y su colaborador Friedrich Engels desarrollaron la teoría comunista en su obra más conocida, el "Manifiesto del Partido Comunista". A lo largo del siglo XX, el comunismo se convirtió en un movimiento político y social global, que tuvo un papel destacado en algunos de los acontecimientos más significativos de la historia reciente, como la Revolución Rusa de 1917, la Segunda Guerra Mundial y la Guerra Fría. A pesar de los esfuerzos por establecer estados socialistas en todo el mundo, muchos de los cuales fracasaron, el comunismo sigue siendo una fuerza política y social importante en algunos países y comunidades.

### Diferencias entre el marxismo y el maoísmo

El marxismo y el maoísmo son dos corrientes políticas y económicas que comparten muchos conceptos, pero también tienen algunas diferencias clave. A continuación se presentan algunas de las principales diferencias entre el marxismo y el maoísmo:

1.  Enfoque en el campesinado: Una de las principales diferencias entre el marxismo y el maoísmo es que este último enfatiza el papel del campesinado en la lucha revolucionaria, mientras que el marxismo se enfoca más en la clase obrera. Mao sostenía que la mayoría de la población en China en ese momento era campesina, y que el campesinado era una fuerza revolucionaria importante.
    
2.  La teoría de la revolución permanente: El marxismo sostiene que la revolución proletaria debe ser internacional y llevar a la abolición del sistema capitalista en todo el mundo, mientras que el maoísmo cree en la posibilidad de una revolución permanente, es decir, una revolución que se extiende de forma continua en el tiempo en un solo país.
    
3.  El papel del Partido Comunista: El marxismo y el maoísmo también tienen diferencias en cuanto al papel del Partido Comunista. Para Mao, el partido debía estar formado principalmente por campesinos, y debía ser el líder de la revolución. El marxismo, por otro lado, sostiene que el partido debe estar compuesto por obreros y liderar la lucha de la clase obrera.
    
4.  La lucha contra el revisionismo: Mao también enfatizó la necesidad de combatir el revisionismo, es decir, la tendencia a revisar o abandonar los principios revolucionarios del comunismo. El marxismo también se opone al revisionismo, pero Mao creía que la lucha contra el revisionismo era especialmente importante en el contexto de la revolución cultural china.
    

En resumen, aunque el maoísmo se basa en gran medida en los principios del marxismo, hay algunas diferencias importantes entre las dos corrientes. El maoísmo enfatiza la importancia del campesinado en la lucha revolucionaria, sostiene que la revolución puede ser permanente y que el partido comunista debe estar compuesto principalmente por campesinos. Además, el maoísmo destaca la lucha contra el revisionismo como un aspecto importante de la teoría comunista.

## Los fundamentos teóricos del marxismo
El marxismo es una teoría política, económica y social basada en las ideas del filósofo y economista alemán Karl Marx. Algunos de los fundamentos teóricos del marxismo son:

1.  Materialismo histórico: Esta teoría sostiene que la evolución de la sociedad se debe principalmente a los cambios en las relaciones de producción, que a su vez están determinados por las fuerzas productivas, es decir, la tecnología, las herramientas y la maquinaria. De acuerdo con el materialismo histórico, la lucha de clases es el motor de la historia.
    
2.  Plusvalía: La teoría de la plusvalía es una de las principales contribuciones de Marx a la economía política. Según esta teoría, el valor de los bienes y servicios producidos por los trabajadores es mayor que el salario que reciben. La diferencia entre el valor del trabajo y el salario es la plusvalía, que se apropia el capitalista como beneficio.
    
3.  Dictadura del proletariado: El objetivo final del marxismo es la abolición de la propiedad privada y la creación de una sociedad socialista, en la que los medios de producción sean propiedad del pueblo. Para lograr esto, Marx propuso la instauración de una "dictadura del proletariado", en la que el proletariado, la clase trabajadora, tomara el poder político y estableciera un gobierno revolucionario que implementara las transformaciones necesarias para llegar al socialismo.
    
4.  Internacionalismo: El marxismo es una teoría internacionalista, que sostiene que la lucha de clases es un fenómeno global. De acuerdo con esta teoría, la solidaridad y la cooperación internacional son esenciales para el triunfo de la revolución proletaria y la creación de una sociedad socialista a nivel mundial.
    
5.  Crítica al capitalismo: Una de las principales críticas del marxismo al capitalismo es que éste genera desigualdad social y explotación de los trabajadores. El capitalismo, según Marx, es un sistema basado en la búsqueda del lucro y la competencia, en el que los trabajadores son tratados como mercancías y explotados para aumentar las ganancias de los capitalistas.

### Las obras de Marx y Engels

Las obras de Marx y Engels son fundamentales para entender el marxismo y su influencia en el movimiento comunista. Algunas de sus obras más importantes son:

-   "El Manifiesto Comunista": escrito por Marx y Engels en 1848, es considerado uno de los textos más influyentes del movimiento comunista. En él se establecen los principios del comunismo y se critica al sistema capitalista.
    
-   "El Capital": obra escrita por Marx en la que se analiza la economía política y se hace una crítica al sistema capitalista. Esta obra es considerada una de las más importantes del marxismo.
    
-   "La Ideología Alemana": obra escrita por Marx y Engels en la que se exponen los principios teóricos del materialismo histórico y se critica a las ideas hegelianas.
    
-   "Manuscritos Económicos y Filosóficos de 1844": obra escrita por Marx en la que se aborda la alienación del trabajo y se critica al sistema capitalista.
    

Estas son solo algunas de las obras más importantes de Marx y Engels, pero su legado intelectual es vasto y ha influenciado a muchas corrientes de pensamiento dentro y fuera del movimiento comunista.

### Los conceptos de plusvalía, lucha de clases, proletariado y burguesía

Plusvalía: La plusvalía es el concepto central en la teoría económica de Marx, que se refiere a la explotación de los trabajadores en un sistema capitalista. Marx argumenta que los trabajadores crean un valor mayor que el que reciben en forma de salarios. La diferencia entre el valor creado y el valor pagado se llama plusvalía, que es apropiada por los dueños de los medios de producción (capitalistas) y no por los trabajadores que generan ese valor.

Lucha de clases: La lucha de clases es el concepto que Marx utiliza para describir la tensión social y política entre dos clases antagónicas: la clase trabajadora y la clase capitalista. Según Marx, la lucha de clases es inevitable en un sistema capitalista, donde los trabajadores son explotados por los capitalistas. Marx argumenta que la única solución a esta tensión es la abolición del sistema capitalista y la creación de una sociedad socialista en la que los medios de producción sean propiedad colectiva y no privada.

Proletariado: El proletariado es la clase trabajadora en un sistema capitalista, que no tiene propiedad sobre los medios de producción y depende de su trabajo para sobrevivir. Marx argumenta que el proletariado es la clase más explotada en un sistema capitalista y que su situación solo puede mejorar si se organiza y lucha contra la clase capitalista.

Burguesía: La burguesía es la clase capitalista en un sistema capitalista, que posee los medios de producción y utiliza el trabajo de los proletarios para generar ganancias. Marx argumenta que la burguesía es la clase dominante en un sistema capitalista y que utiliza su poder económico para mantener a los trabajadores en una situación de explotación y pobreza.

### La crítica al capitalismo y la propuesta de la sociedad comunista

La crítica al capitalismo y la propuesta de la sociedad comunista son aspectos centrales del marxismo. Marx y Engels criticaron el capitalismo por ser un sistema que explota a los trabajadores y beneficia a la clase capitalista, lo que resulta en desigualdades económicas y sociales.

La propuesta de la sociedad comunista se basa en la idea de que la propiedad privada debe ser abolida y los medios de producción deben ser propiedad común de la sociedad. Esto permitiría la distribución equitativa de los recursos y acabaría con la explotación de los trabajadores.

En la sociedad comunista, se espera que no haya clases sociales, ya que la propiedad común eliminaría las diferencias económicas entre las personas. El trabajo sería voluntario y estaría dirigido a la producción de bienes y servicios necesarios para la sociedad en su conjunto. La sociedad se organizaría en torno a la planificación económica centralizada, lo que permitiría una distribución eficiente de los recursos y una reducción de los desechos y la sobreproducción.

## El desarrollo del maoísmo en China
El maoísmo se originó en China durante la primera mitad del siglo XX bajo el liderazgo de Mao Zedong, quien fue el líder del Partido Comunista Chino desde 1949 hasta su muerte en 1976. Mao desarrolló y adaptó el marxismo-leninismo a las condiciones específicas de China, lo que llevó a la creación del maoísmo.

El maoísmo se basa en la idea de que la revolución debe ser llevada a cabo por las masas populares, lideradas por la clase obrera, y no por una élite revolucionaria. Mao también enfatizó la importancia de la lucha armada y la guerrilla como tácticas revolucionarias efectivas.

Durante su liderazgo, Mao implementó diversas políticas y programas, incluyendo la Gran Marcha y la Revolución Cultural, que tuvieron un impacto significativo en la sociedad y la economía chinas. Aunque algunas de estas políticas se consideran controvertidas y han sido criticadas, muchas personas consideran a Mao como un héroe nacional y un líder revolucionario.

Después de la muerte de Mao, el maoísmo continuó influyendo en la política y la sociedad de China y en otros países que adoptaron el maoísmo como ideología.
### La Revolución Cultural y el pensamiento de Mao Zedong

La Revolución Cultural fue un movimiento político y social que tuvo lugar en la República Popular China desde 1966 hasta 1976. Fue lanzada por el líder del Partido Comunista de China, Mao Zedong, con el objetivo de consolidar su poder y promover su visión del comunismo.

Durante la Revolución Cultural, se buscó eliminar cualquier vestigio del pensamiento capitalista o burgués y se promovió la igualdad social y la colectivización de la propiedad. La Revolución Cultural se caracterizó por la violencia y la represión contra aquellos considerados enemigos del movimiento, incluyendo intelectuales, artistas y otros disidentes políticos.

El pensamiento de Mao Zedong, también conocido como maoísmo, se basó en gran medida en la lucha de clases y la importancia de la movilización popular para lograr el cambio social. Mao creía que la revolución no podía ser liderada por una élite intelectual, sino que debía ser impulsada por las masas populares.

En términos políticos, Mao abogaba por un sistema de democracia popular en el que el poder residiera en las manos del pueblo y no en las de una élite burocrática. También promovió la autarquía económica y la independencia de China de las potencias extranjeras.

El legado de Mao Zedong y la Revolución Cultural sigue siendo objeto de controversia y debate. Algunos lo consideran como una figura importante en la historia de China y en la lucha contra el imperialismo y el capitalismo, mientras que otros lo ven como un dictador responsable de graves violaciones a los derechos humanos.

### El papel del campesinado y la teoría de las tres fuentes del marxismo

La teoría de las tres fuentes del marxismo es un concepto clave del maoísmo y sostiene que el marxismo es la combinación de tres corrientes ideológicas: la economía política clásica británica, el socialismo utópico francés y la filosofía alemana.

El campesinado ocupa un lugar importante en la teoría maoísta, y Mao sostenía que era el principal actor revolucionario en países como China, donde la mayoría de la población vivía en zonas rurales. Mao creía que el campesinado era más capaz de llevar a cabo una revolución que el proletariado industrial, ya que el primero estaba más cerca de la realidad de la opresión y la explotación.

En este sentido, Mao propuso la estrategia de la "guerra popular prolongada", que consistía en que el campesinado se organizara en grupos guerrilleros y llevara a cabo una guerra de guerrillas contra las fuerzas armadas del gobierno, lo que eventualmente llevaría a la victoria de la revolución comunista.

Mao también creía que el campesinado podía ser educado y movilizado para desarrollar una conciencia revolucionaria y llevar a cabo una transformación social en China y en otros países en vías de desarrollo. Por tanto, Mao creía que la alianza entre el campesinado y el proletariado era la clave para llevar a cabo la revolución comunista.

### La influencia del maoísmo en otros países, especialmente en América Latina

El maoísmo tuvo una gran influencia en varios países de América Latina en la década de 1960 y 1970, especialmente en aquellos que estaban experimentando procesos revolucionarios o tenían fuertes movimientos campesinos y obreros. Algunos de los países más afectados por esta influencia fueron Perú, Colombia, Chile, Argentina y México.

En Perú, el maoísmo fue liderado por el Partido Comunista del Perú-Sendero Luminoso, que buscaba la creación de una sociedad comunista a través de una lucha armada contra el Estado peruano. La organización tuvo un gran impacto en la década de 1980, pero fue finalmente derrotada por el gobierno.

En Colombia, el maoísmo se manifestó a través del Ejército de Liberación Nacional (ELN), que también buscaba la lucha armada para alcanzar sus objetivos revolucionarios. El ELN sigue siendo una de las organizaciones guerrilleras activas más grandes de América Latina.

En Chile, el Movimiento de Izquierda Revolucionaria (MIR) adoptó el maoísmo como su principal influencia ideológica. El MIR jugó un papel importante en la lucha contra la dictadura de Augusto Pinochet, pero fue finalmente derrotado y disuelto en la década de 1980.

En Argentina, el maoísmo se manifestó a través del Partido Revolucionario de los Trabajadores (PRT), que también buscaba la lucha armada para alcanzar la revolución socialista. El PRT fue uno de los grupos más activos en la década de 1970, pero fue finalmente derrotado por la represión estatal.

En México, el maoísmo tuvo una influencia significativa en el Partido de los Pobres y en el Ejército Revolucionario del Pueblo Insurgente (ERPI), que también buscaron la lucha armada para lograr sus objetivos revolucionarios. Sin embargo, estos grupos no tuvieron el mismo nivel de éxito que otros movimientos maoístas en América Latina.


## Análisis crítico del comunismo marxista y maoísta

Como modelo político, el comunismo marxista y maoísta ha sido objeto de numerosas críticas a lo largo de la historia. Algunas de estas críticas se centran en el hecho de que estos modelos políticos no han logrado producir los resultados económicos y sociales esperados, y en su lugar han generado represión y violencia. Además, se ha argumentado que el marxismo y el maoísmo son sistemas políticos que tienden a la centralización del poder, lo que a menudo ha dado lugar a regímenes autoritarios y totalitarios.

Otras críticas se han centrado en la capacidad del comunismo para fomentar la innovación y la creatividad, ya que algunos argumentan que la falta de incentivos económicos en una economía comunista puede desalentar la innovación y la producción de bienes y servicios de alta calidad. También se ha criticado la falta de libertades individuales y la ausencia de un sistema de mercado que permita a los ciudadanos ejercer su libre elección.

Sin embargo, los defensores del comunismo argumentan que los fracasos de los modelos comunistas han sido el resultado de la aplicación incorrecta de los principios teóricos, y no una falla inherente del sistema en sí. Además, se ha argumentado que el comunismo ha sido capaz de proporcionar igualdad económica y social a las personas y ha permitido el acceso a los recursos a toda la población, algo que no ha sido posible en otros sistemas políticos.

En última instancia, el debate sobre el comunismo marxista y maoísta sigue siendo controvertido y sigue siendo objeto de intenso debate en todo el mundo.

### Críticas externas al comunismo, como la de los economistas neoliberales

Los economistas neoliberales, como Friedrich Hayek y Milton Friedman, han sido críticos severos del comunismo y han argumentado que el control estatal de los medios de producción es ineficiente y socava la libertad individual. Hayek, en particular, argumentó que el socialismo y el comunismo conducirían inevitablemente a una sociedad totalitaria en la que el estado controlaría todos los aspectos de la vida y se erosionaría la libertad individual.

Friedman también argumentó que el control estatal de la economía es ineficiente y que la competencia y el mercado libre son esenciales para el éxito económico. Él y otros economistas neoliberales también han criticado la idea de que la igualdad económica y social es deseable o posible, argumentando que esto lleva a la pobreza generalizada y al estancamiento económico.

Sin embargo, los defensores del comunismo argumentan que estas críticas ignoran el hecho de que el capitalismo también tiene sus propios problemas, como la desigualdad económica, la pobreza y la explotación laboral. También sostienen que la libertad individual no puede ser completa en un sistema capitalista que está dominado por la búsqueda del lucro y la propiedad privada.

### Críticas internas, como las diferencias entre las diversas corrientes comunistas

Las críticas internas al comunismo son variadas y provienen de diferentes corrientes dentro del propio movimiento comunista. A continuación, se presentan algunas de las principales críticas:

1.  Dificultad para implementar la teoría en la práctica: algunos críticos argumentan que el comunismo es una teoría atractiva en papel, pero difícil de implementar en la práctica debido a la complejidad del ser humano y la realidad social y económica.
    
2.  Falta de libertades individuales: algunos críticos argumentan que el comunismo suprime la libertad individual y la iniciativa privada, lo que puede conducir a una pérdida de creatividad y a una economía menos eficiente.
    
3.  Problemas de planificación centralizada: algunos críticos argumentan que la planificación centralizada del comunismo puede ser ineficiente y generar escasez de recursos y productos, ya que los planificadores no pueden prever las necesidades y demandas cambiantes de la sociedad.
    
4.  Tendencia a la opresión y la dictadura: algunos críticos argumentan que el comunismo, al otorgar tanto poder al Estado, puede conducir a la opresión y la dictadura, y que la falta de mecanismos de control y equilibrio puede generar abusos y violaciones a los derechos humanos.
    

Es importante destacar que estas críticas no son compartidas por todas las corrientes comunistas, y que existen visiones diferentes sobre cómo abordar estos problemas.

### Reflexiones sobre las lecciones del pasado y las posibilidades de futuro del comunismo

El comunismo ha sido uno de los movimientos políticos más influyentes del siglo XX, aunque también ha sido objeto de críticas y controversias. A medida que ha pasado el tiempo, ha surgido una variedad de interpretaciones sobre lo que significa ser comunista y cómo se debe llevar a cabo una revolución comunista.

Una reflexión importante sobre las lecciones del pasado es que la revolución comunista no ha sido fácil de implementar. En muchos casos, ha habido violencia y represión, y algunos han argumentado que estos problemas son inherentes al comunismo. Otros, sin embargo, han argumentado que estos problemas son el resultado de la falta de comprensión de los principios comunistas.

En cuanto a las posibilidades de futuro del comunismo, algunos han argumentado que el comunismo es una idea obsoleta que ha sido superada por los acontecimientos históricos. Otros, sin embargo, han argumentado que el comunismo sigue siendo una fuerza vital en la política mundial y que sigue siendo relevante en el siglo XXI.

En última instancia, la viabilidad del comunismo como sistema político depende de la capacidad de sus teóricos y defensores para abordar los problemas y críticas que se han planteado en el pasado, y de la capacidad de las sociedades para implementar el comunismo de manera efectiva y justa. En cualquier caso, el comunismo sigue siendo una teoría y una práctica política fascinante e influyente que ha transformado el mundo de muchas maneras.

## Comunidad y acción política
###  Los movimientos políticos en la actualidad
Hay muchos movimientos políticos en todo el mundo en la actualidad. Algunos de los más destacados incluyen:

1.  Movimientos populistas de derecha: Estos movimientos se caracterizan por su retórica nacionalista y su oposición a la inmigración y la globalización. Ejemplos incluyen el partido de gobierno en Hungría, Fidesz, y el partido Alternativa para Alemania (AfD).
    
2.  Movimientos progresistas: Estos movimientos se enfocan en cuestiones como la justicia social, la igualdad de género y el medio ambiente. Ejemplos incluyen el movimiento Black Lives Matter en los Estados Unidos y el partido Podemos en España.
    
3.  Movimientos nacionalistas y separatistas: Estos movimientos buscan la independencia de una región o grupo étnico dentro de un país. Ejemplos incluyen el movimiento independentista catalán en España y el Partido Nacionalista Escocés en el Reino Unido.
    
4.  Movimientos de protesta: Estos movimientos a menudo surgen en respuesta a eventos específicos, como elecciones controvertidas o la violencia policial. Ejemplos incluyen las protestas en Hong Kong y las protestas por la muerte de George Floyd en los Estados Unidos.
    
5.  Movimientos religiosos: Estos movimientos buscan promover la religión y sus valores en la política. Ejemplos incluyen el partido Justicia y Desarrollo en Turquía y el partido Bharatiya Janata en India.
    

Cada uno de estos movimientos políticos tiene sus propias características y objetivos únicos, y su impacto en la política y la sociedad varía de un lugar a otro.

### La importancia de las organizaciones políticas y la movilización popular

Las organizaciones políticas y la movilización popular son fundamentales para el cambio social y político. Las organizaciones políticas pueden ser partidos políticos, grupos de acción directa, organizaciones comunitarias y sindicatos, entre otros. Estas organizaciones trabajan para representar a sus miembros y avanzar en sus objetivos políticos, ya sea a través de la participación en elecciones, la presión sobre los tomadores de decisiones o la creación de programas y servicios para la comunidad.

La movilización popular se refiere a la acción colectiva de las personas para lograr un cambio político o social. Esto puede incluir manifestaciones, huelgas, boicots, protestas y otras formas de acción directa. La movilización popular es una forma poderosa de influir en las políticas y prácticas gubernamentales, y ha sido fundamental para muchos movimientos sociales y políticos.

Sin embargo, tanto las organizaciones políticas como la movilización popular pueden enfrentar desafíos. Las organizaciones pueden verse obstaculizadas por la falta de recursos, la falta de participación de los miembros y la lucha por el liderazgo interno. La movilización popular puede verse obstaculizada por la represión estatal y la falta de apoyo público.

A pesar de estos desafíos, la comunidad y la acción política siguen siendo fundamentales para el cambio social y político. Las personas y las organizaciones que trabajan juntas pueden lograr cambios significativos y avanzar hacia una sociedad más justa y equitativa.

### La práctica política en relación al comunismo marxista y maoísta

La práctica política en relación al comunismo marxista y maoísta es esencialmente la implementación de los principios y teorías desarrolladas por Marx, Engels y Mao. Ambas corrientes buscan la emancipación del proletariado y la eliminación del sistema capitalista, aunque difieren en algunos aspectos teóricos y prácticos.

En el caso del marxismo, se enfoca en la construcción de un partido político proletario que dirige la revolución socialista. El partido debe estar comprometido con la educación y la organización de la clase obrera, así como con la lucha política para tomar el poder estatal y transformar la sociedad en beneficio de la mayoría trabajadora.

Por otro lado, el maoísmo hace énfasis en la participación del campesinado y otros sectores populares en la lucha revolucionaria, lo que se refleja en la teoría de las tres fuentes del marxismo. Mao consideraba que el campesinado tenía un papel fundamental en la construcción del socialismo y que la revolución no debía limitarse a los centros urbanos, sino que debía extenderse a las áreas rurales y semi-feudales.

En términos prácticos, ambos enfoques buscan la organización de las masas y la movilización popular para la transformación de la sociedad, pero difieren en los métodos y estrategias para lograrlo. En cualquier caso, la práctica política en el comunismo marxista y maoísta debe estar enraizada en los principios teóricos y en la realidad concreta del contexto político y social en que se desarrolla.
